MagicMirrorOrg/MagicMirror-Documentation

- modules/configuration.md
Explicitly written out that the classes option for modules in the config.js is a list of CSS selectors. I was reading the docs and missed this information.
> Clarify that the "classes" option is a list

- modules/weather.md
After just receiving the notification about the new release, it reminded me to update the docs for the new provider.
I also fixed the screenshots as I noticed their paths were set incorrectly.
> Add config guide for Met Office DataHub weather provider

- modules/currentweather.md
Adds documentation of configuration option to hide sunrise/sunset in the default Current Weather module.
Configuration option is `showSun` to match the addition to the default Weather module.
Appropriate [pull request](https://github.com/MichMich/MagicMirror/pull/2059) also submitted to [MagicMirror](https://github.com/MichMich/MagicMirror).
> added config option to hide sunrise/sunset in Current Weather module

- README.md
Currently there is no direct link from the documentation root back to the homepage.
> Add a link back to the homepage

- .vuepress/config.js
- README.md
- development/documentation.md
- development/notifications.md
- getting-started/autostart.md
- getting-started/configuration.md
- modules/alert.md
- modules/calendar.md
- modules/clock.md
- modules/currentweather.md
- modules/customcss.md
- modules/newsfeed.md
- modules/weather.md
- modules/weatherforecast.md
This PR moves some pages from the wiki to the more visible Documentation page as discussed in https://github.com/MichMich/MagicMirror/issues/2545:
- Notifications in the MM
- Autostarting your MM
- How to write Documentation for your own module
- Syncing infos for your calendars
Also the pages use https for all links now.
> Add some pages from wiki to the docs

- getting-started/installation.md
- getting-started/upgrade-guide.md
* this improves install speeds dramatically
* tested with `npm run server` on NPM v6 and v8 (but please test yourself again as I couldn't spin up a desktop environment for `npm run start`)
using `--only=prod` for legacy npm clients (https://docs.npmjs.com/cli/v6/commands/npm-install)
using `--omit=dev` for v7+(https://docs.npmjs.com/cli/v7/commands/npm-install)
> update npm install command to exclude dev dependencies

- modules/alert.md
- modules/calendar.md
Fixes the *Font Awesome* url.
I'm not quite sure if `v4.7` is the correct version to link, but at least some icons from `v5.x` (recent) don't work.
> fix: correct url to awesome font

- modules/currentweather.md
migration guide for currentweather module should show "currentweather" for the old module name instead of "weatherforecast"
> update migration guide

- README.md
Hi!
I noticed that when looking at the documentation project page in GitHub, the logo was missing. The file header.png is already in the `./vuepress/public` folder so I changed it to that path.
Please check that in the final VuePress build of the documentation the logo is also there (it was in my local test).
Kind regards,
-Thomas
> docs(Magic Mirror doc): :memo: fixed the path to header.png in README.md

- modules/weather.md
This PR aims to keep the docs up-to-date with https://github.com/MichMich/MagicMirror/pull/2902
> Add `location` config option to SMHI weather provider

- getting-started/installation.md
With `--no-audit` these warnings should not appear, right?
> Remove High Security Alert note

- getting-started/installation.md
- getting-started/upgrade-guide.md
- remove docker sentence in server only description which was a restriction of old docker setup, current docker setup runs on raspberry pi and as server only
- update upgrade command to command used for install
can be merged immediately, has not to wait for next release
> minor changes

- configuration/introduction.md
introduced with https://github.com/MichMich/MagicMirror/pull/3032, related to https://github.com/MichMich/MagicMirror/issues/1756
> add doc for environment variables

- modules/weather.md
Adding documentation for [related feature](https://github.com/MichMich/MagicMirror/pull/3178)
> `allowOverrideNotification` Documentation

- getting-started/requirements.md
- modules/calendar.md
I used `master` as base branch because this can merged immediately because
- node18 reaches end of life in a few days
- digest auth in calendar is not working since mm release `2.15.0`
> add node18 as required, remove digest from calendar auth

- modules/weather.md
Comparable update to pull #3499 in the main repo. 
UK Met Office DataHub section updated to remove the api secret and updated the base api Uri.
> UK Met Office Documentation Fix

- development/core-module-file.md
- development/notifications.md
- package-lock.json
- yarn.lock
Fixes #261 
Discussion of new notification: https://github.com/MagicMirrorOrg/MagicMirror/issues/3534.
> Added docs for new notification `MODULE_DOM_UPDATED`

- about/contributing.md
- cspell.config.json
I would like to propose this update to our Contributing Guidelines regarding the working language. While English has always been our de facto working language, it hasn't been explicitly stated in our documentation. Recently, we have received contributions in other languages, which highlighted the need for clearer guidelines to ensure smooth communication and collaboration within our diverse community.
Side note: I personally struggle with English myself, and in an ideal world, I would choose another language as working language (Esperanto, of course). However, I accept the reality and see this as the most viable solution for our community.
> Add Working Language

- modules/newsfeed.md
documentation update for https://github.com/MagicMirrorOrg/MagicMirror/pull/3742 which comes with next mm release
> newsfeed: add new properties for feeds

- configuration/autostart.md
- configuration/introduction.md
- getting-started/installation.md
fixes #303 
I replaced all occurrences, not only the one concerning windows, I think it is clearer not to use the abbreviation `npm start` in the docs.
> replace `npm start` with `npm run start`

- getting-started/upgrade-guide.md
The last two times I have tried to upgrade MM, I have encountered errors because my node version was not correct.  Thus, I think we should include information here about how one would properly go about upgrading node.  I have included in this PR what works for me, but I am FAR from an expert in node.
> Add instructions for upgrading node when upgrade of MM fails

- .github/workflows/autoupdate_develop.yaml
see #311 
use secret which has contents rw access for pulling/pushing
The used secret must be approved by an org admin @rejas (I requested twice, need approval for latest request, did delete the first one)
It must be renewed yearly
> update automerge workflow

- README.md
- cspell.config.json
- development/introduction.md
- modules/introduction.md
I consider Deepwiki to be a very interesting project and think that it can be a good addition to our official documentation. Therefore, I propose mentioning it in the documentation.
See: https://deepwiki.com/MagicMirrorOrg/MagicMirror.
> Add reference to Deepwiki
