MagicMirrorOrg/MagicMirror-Documentation

- modules/updatenotification.md
Documentation for changes in this PR: https://github.com/MichMich/MagicMirror/pull/1929
> Adding ignoreModules documentation

- getting-started/installation.md
After the discussions in https://github.com/MichMich/MagicMirror/issues/1860 the result may should be mentioned in the installation methods.
Feel free to edit my english ...
> some fixes reflecting current version v2.11.0, added MagicMirrorOS

- modules/weather.md
Update `locationId` with `locationID`.
> Update Met Office options

- getting-started/installation.md
Hi,
wrote a helm chart for kubernetes setup, would be happy to find it in the documentation.
Thanks,
Karsten.
> add Kubernetes setup

- modules/weather.md
Related to: https://github.com/MichMich/MagicMirror/pull/2032
> [weather] Added new config parameter

- modules/compliments.md
I really struggled to get this to work until Sam on the forums helped me. I thought this should be added to the docs to avoid anyone else having this issue in the future. 
Apologies if the formatting isn't very good, I am not very knowledgable or experienced with markdown.
> Example config of a Compliment file hosted on Github

- modules/alert.md
- modules/calendar.md
"Font Awsome" => "Font Awesome" in alert.md, calendar.md
> Fix "Font Awsome" typo

- modules/weatherforecast.md
Documentation for https://github.com/MichMich/MagicMirror/pull/2078
> Lat/Lon support for onecall API

- modules/calendar.md
For what it's worth: This is NOT Hacktoberfest spam (I'm not participating); I just noticed as I was reading through the setup guide.
> Address typo in url description

- getting-started/configuration.md
Minor tweak to the doc - these clauses should be in one sentence.
> Update configuration.md with grammar fix

- modules/weather.md
Keeping the documentation updated with the newly accepted provider.
> Adding documentation for SMHI as weather provider

- modules/weather.md
Updates documentation to include options for Weatherbit, MM pull request 2187 and released to master branch on Jan 1, 2021.
> Weather Module Documentation Update for Weatherbit

- README.md
- package.json
Needed a way to actually run the documentation so I added scripts for it and updated the Readme to be more about the actual documentation than the MagicMirror project itself.
> Updating Readme with instructions for running the documentation locally

- getting-started/installation.md
Ran into some problems on a fresh install. Found the solutions on the forums. 
Didn't verify that the markdown displays properly in the docs, so let me know if there are any formatting errors.
> Add fixes for common installation issues

- development/core-module-file.md
https://github.com/MichMich/MagicMirror/pull/2439
> Add onError callback in show

- .vuepress/config.js
- modules/customcss.md
Created a new page about customizing the look of magicmirror using the custom.css feature with an example and a link to the forum.
> Adding a bit of documentation about the custom css

- getting-started/installation.md
This update is related to the follwing issues:
- https://github.com/MichMich/MagicMirror/issues/2555
- https://github.com/MichMich/MagicMirror/issues/2471
Feel free to change if something is not in your mind.
> update installation.md concerning node version and docker setup

- modules/newsfeed.md
This option was introduced with #2580.
> Add description for 'showAsList'

- modules/weather.md
I'm assuming I'm following the correct process for MM doc updates :) 
I have updated weather.md to include the config/usage details for the new Environment Canada provider. Please let me know if I need to something else!
> Weather modules updates for new Environment Canada provider

- .vuepress/config.js
- development/weather-provider.md
- package-lock.json
- package.json
- yarn.lock
This tutorial was in the sourcecode of the core repo (https://github.com/MichMich/MagicMirror/blob/master/modules/default/weather/providers/README.md)
I think it fits better here together with the other development info.
Will open a PR to remove it from the core next.
> Add info about how to develop a weather provider

- getting-started/installation.md
- getting-started/requirements.md
- package-lock.json
- package.json
- yarn.lock
... like windows
Makes https://github.com/MichMich/MagicMirror/pull/2698 irrelevant
> Add info on how to run MM on other OS

- getting-started/installation.md
- getting-started/requirements.md
updates in documentation for https://github.com/MichMich/MagicMirror/issues/2740
> update node version to v16

- development/node-helper.md
I don't have a module with this stop function, but it should work.
> console -> Log

- development/node-helper.md
> var -> const

- modules/weather.md
related to PR https://github.com/MichMich/MagicMirror/pull/2798
> update weather documentation concerning cors and darksky

- getting-started/installation.md
- getting-started/upgrade-guide.md
- modules/newsfeed.md
- add new option `showTitleAsUrl` in newsfeed module
- remove references of dead docker setup https://github.com/bastilimbach/docker-MagicMirror
- added warning in upgrade guide
> update newsfeed module and minor changes

- modules/weather.md
I added the docs for the weather provider Weatherflow. See also https://github.com/MichMich/MagicMirror/pull/2815
> add docs for  Weatherflow weather provider

- modules/configuration.md
- package-lock.json
- package.json
- yarn.lock
also update dependencies
Fixes https://github.com/MichMich/MagicMirror/issues/2841
> Correct internal link

- getting-started/installation.md
In reference to  https://github.com/MichMich/MagicMirror/issues/2860
> Add verbiage to ignore security alert.

- getting-started/installation.md
see https://github.com/MichMich/MagicMirror/pull/2891
This PR should be merged with the next mm release Oct. 2022, not before.
> change install command to new `npm run install-mm`

- modules/calendar.md
This pull request is accompanied by [this one](https://github.com/MichMich/MagicMirror/pull/2881) in the MagicMirror repo.
> add documentation for manually fetching calendars

- getting-started/installation.md
I haven't tested it, but `postinstall` should take care of this by now.
> Remove vendor and font part for Windows

- modules/newsfeed.md
see https://github.com/MichMich/MagicMirror/pull/2940 and https://github.com/MichMich/MagicMirror/issues/2999
> add doc for newsfeed module concerning useCorsProxy

- getting-started/installation.md
Reverts MichMich/MagicMirror-Documentation#136
> Revert "Remove vendor and font part for Windows"

- .vuepress/config.js
- development/core-module-file.md
- development/helper-methods.md
- development/node-helper.md
- development/notifications.md
- getting-started/requirements.md
- getting-started/upgrade-guide.md
- modules/introduction.md
- package.json
- yarn.lock
Noticed that one link to operating systems was broken, so I added a link checker and cleaned up the markdown where the checker reported errors and warnings. 
Can be merged immediatly.
> Add link checker and cleanup links

- modules/updatenotification.md
> updatenotification.md: mention excluding MagicMirror

- configuration/introduction.md
- getting-started/installation.md
- getting-started/requirements.md
- getting-started/upgrade-guide.md
- package-lock.json
- package.json
- yarn.lock
as mentioned here, add note about stretch based raspbian versions: https://github.com/MichMich/MagicMirror/issues/2989
- add note about debian stretch based os 
- rename raspbian to raspberry pi os
- cleanups and typos
> Cleanup required OS infos

- modules/updatenotification.md
update of `updatenotification` doc
I don't use vuepress, I hope the syntax is correct and in accord with it
@rejas: tell me if it's good ;)
> updatenotification: add `sendUpdatesNotifications` feature, `SCAN_UPDATES` and `UPDATES` notifications

- development/weather-provider.md
- getting-started/installation.md
- getting-started/upgrade-guide.md
I just saw a "weird" display with  warning/danger blocks
let's correct it in accord with [VuePress docs](https://vuepress.vuejs.org/guide/markdown.html#default-title)
> correct block in docs

- development/node-helper.md
> correct node-helper.md

- development/core-module-file.md
- better reading from md file
- correct final displaying (missing some br tag)
To see in develop POV if it's better before merging
> correct core-module-file

- development/core-module-file.md
- development/node-helper.md
some payload params were formatted wrong
> Fix param formatting

- getting-started/requirements.md
- modules/calendar.md
- package-lock.json
- package.json
- yarn.lock
Removed digest from calendar docs
Added note about Node18 requirement
> Update digest and node info

- getting-started/installation.md
> update installation instructions

- development/introduction.md
I thought I saw this recommendation somewhere, but I can't find it in the documentation.
> Module name pattern recommendation

- development/core-module-file.md
> Fix links to animation guide

- development/weather-provider.md
- getting-started/installation.md
- getting-started/upgrade-guide.md
- package-lock.json
- yarn.lock
noticed that some of those infoboxes didnt have a linebreak after the severity tag, so this PR adds them.
> Fix some infoboxes

- configuration/introduction.md
Forgot quotes in basic configuration, bug found in main.
Fixes #227
> Fix quotes in documentaion

- modules/updatenotification.md
updatenotification update docs #222
> add updates feature configuration

- configuration/autostart.md
- development/core-module-file.md
- development/helper-methods.md
- development/notifications.md
- development/weather-provider.md
- getting-started/upgrade-guide.md
- modules/animate.md
- modules/calendar.md
- wording
- Magic Mirror -> MagicMirror
- format
> Minor changes

- development/logger.md
This adds a reminder that logs can appear in the web browser console as well.
> Add Note About Where to Check for Logs

- README.md
> badges: fix checks-badge, remove codecov-badge

- getting-started/installation.md
According to the changes in PR https://github.com/MagicMirrorOrg/MagicMirror/pull/3594.
> Update Windows section and add Wayland section

- getting-started/installation.md
- getting-started/requirements.md
see discussion in forum or https://github.com/MagicMirrorOrg/MagicMirror/issues/3629
> update required node version

- development/node-helper.md
electron-rebuild has been deprecated.
> electron-rebuild -> @electron/rebuild

- .github/workflows/autoupdate_develop.yaml
> add workflow to autoupdate develop branch
